[package]
name = "osqp-sys"
version = "0.2.1-pre.1"
description = "FFI bindings to the OSQP (Operator Splitting Quadratic Program) solver."
authors = ["Edward Barnard <eabarnard@gmail.com>"]
license = "MIT/Apache-2.0"
links = "osqp"

[build-dependencies]
cmake = "0.1.28"
